AdminWebSite/Controllers/OrderDetailController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminWebSite.Models;
using Microsoft.Reporting.WebForms;


namespace AdminWebSite.Controllers
{
    public class OrderDetailController : Controller
    {
        private DBWatchEntities db = new DBWatchEntities();
        // GET: OrderDetail
        public ActionResult Reports()
        {
            var orderDetail = db.OrderDetail.Include(o => o.Order).Include(o => o.Product);
            return View(orderDetail.ToList());
        }      


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LeoShop</title>
    <!-- plugins:css -->
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/pages/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/datatables/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/Content/datatables/bootstrap.min.css" rel="stylesheet" />
    <!-- endinject -->
    <link rel="shortcut icon" href="~/Content/images//favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            @{
                Html.RenderPartial("_Navbar");
            }
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            @Html.Partial("_SliderBar")
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="container-fluid clearfix">
                        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018 Leo Shop - Watch Shop. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/Content/datatables/jquery.min.js"></script>
    <script src="~/Content/datatables/jquery.dataTables.js"></script>
    <script src="~/Content/datatables/dataTables.bootstrap4.js"></script>
    <script src="~/Content/js/sb-admin-datatables.min.js"></script>
    <script src="~/Content/js/sb-admin-datatables.min.js"></script>
    <script src="~/Content/js/sb-admin-datatables.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <!-- End custom js for this page-->

</body>
</html>

AdminWebSite/Views/Shared/_Navbar.cshtml
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <a class="navbar-brand brand-logo" href="index.html"><img src="~/Content/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/Content/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center">
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>

AdminWebSite/Views/Shared/_SliderBar.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <div class="nav-link">
                <div class="profile-image"> <img src="~/Content/images/faces/face4.jpg" alt="image" /> <span class="online-status online"></span> </div>
                <div class="profile-name">
                    <p class="name">Richard V.Welsh</p>
                    <p class="designation">Manager</p>
                </div>
            </div>
        </li>
        <li class="nav-item"><a class="nav-link" href="/AdminCategories/Index"><img class="menu-icon" src="~/Content/images/menu_icons/06.png" alt="menu icon"><span class="menu-title">Categories</span></a></li>
        <li class="nav-item"><a class="nav-link" href="/AdminBrands/Index"><img class="menu-icon" src="~/Content/images/menu_icons/02.png" alt="menu icon"><span class="menu-title">Brands</span></a></li>
        <li class="nav-item"><a class="nav-link" href="/AdminProducts/Index"><img class="menu-icon" src="~/Content/images/menu_icons/03.png" alt="menu icon"><span class="menu-title">Products</span></a></li>
        <li class="nav-item"><a class="nav-link" href="/AdminCustomers/Index"><img class="menu-icon" src="~/Content/images/menu_icons/04.png" alt="menu icon"><span class="menu-title">Customers</span></a></li>
        <li class="nav-item"><a class="nav-link" href="/AdminOrders/Index"><img class="menu-icon" src="~/Content/images/menu_icons/05.png" alt="menu icon"><span class="menu-title">List Order Details</span></a></li>
        <li class="nav-item"><a class="nav-link" href="/OrderDetail/Report"><img class="menu-icon" src="~/Content/images/menu_icons/05.png" alt="menu icon"><span class="menu-title"> @Html.ActionLink("List Report","Reports","OrderDetail")</span></a></li>

        @*<li class="nav-item">
            <div class="collapse" id="general-pages">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/blank-page.html">Blank Page</a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html">Login</a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html">Register</a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/error-404.html">404</a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/error-500.html">500</a></li>
                </ul>
            </div>
        </li>*@

    </ul>
</nav>